disable OSX CI test
Currently the CI fails due to the issue
```
Error: homebrew/science was deprecated. This tap is now empty as all its formulae were migrated.
The command "if [ $TRAVIS_OS_NAME = osx ]; then brew update; brew tap homebrew/science; fi" failed and exited with 1 during .
```

Until the fix is implemented the OSX tests will be disabled.